### ISSUE TITLE
[BUG] Error creating machine: Error running provisioning: Error running "sudo apt-get update": ssh command error:

### ISSUE THREAD

**Issue by vistalba** [mxschmitt/ui-driver-hetzner#42]
If creating a node with hetzner driver and a cloud-init script in template results in error:

`Error creating machine: Error running provisioning: Error running "sudo apt-get update": ssh command error:`

cloud-init script:
```
#cloud-config
locale: de_CH.UTF-8
timezone: Europe/Berlin
package_update: true    # Implied with `package_upgrade: true`
#package_upgrade: true
packages:
 - tree
 - screen
 - apt-transport-https
 - ca-certificates
 - curl
 - software-properties-common
 - nload
 - htop
 - jq
#package_reboot_if_required: true
users:
# Create new user `user1`
  - name: user1
    groups: sudo
    lock_passwd: false
    shell: /bin/bash
    passwd: $6$...
    ssh-authorized-keys:
      - ssh-rsa A...r
  - name: root
    ssh-authorized-keys:
      - ssh-rsa A...d
# Configure SSH
runcmd:
  - sed -i 's/#HostKey \/etc\/ssh\/ssh_host_ed25519_key/HostKey \/etc\/ssh\/ssh_host_ed25519_key/g' /etc/ssh/sshd_config
  - sed -i 's/[#]*PermitRootLogin yes/PermitRootLogin prohibit-password/g' /etc/ssh/sshd_config
  - sed -i 's/[#]*PasswordAuthentication yes/PasswordAuthentication no/g' /etc/ssh/sshd_config
  - /etc/init.d/ssh restart
```

I already tried to comment out some lines of my cloud-init script to find the problem but it didn't help :( If I remove the whole script from template the provisioning is working normal.

If I use the cloud-init script in Hetzner Cloud Console directly, it works also.

OS: Ubuntu 18.04
Sizeing: CX21
Datacenter: nbg
Dockerversion: 18.09
Rancher: v2.2.5
